// !commands
import './ping';
import './intent';
import './remember';
import './context';
import './amber';
import './github';
import './wakatime';
import './summary';
import './trait';
import './chat';
import './instruct';
